// src/web/app/[locale]/authenticate/page.tsx
'use client';
import React from 'react';
import { useTranslations } from 'next-intl';
import { Button, Divider, Link } from '@nextui-org/react';
import { AuthenticateUISettings } from '@/app/models/authenticate-ui-settings';
import ThemeSwitcher from '@/app/components/ThemeSwitcher';
import LanguageSwitcher from '@/app/components/LanguageSwitcher';
import { signIn } from 'next-auth/react';

const Authenticate = () => {
    const authenticateSettings: AuthenticateUISettings = {
        domain: 'chnu.edu.ua',
        logo: '/images/logo-chnu.svg',
        backgroundImage: '/images/chnu-front.jpg',
        links: {
            tiktok: '',
            youtube: '',
            website: '',
        },
    };

    const login = async () => {
        await signIn('google', { callbackUrl: `/profile` });
    };

    const t = useTranslations('authenticate');

    return (
        <div className='flex w-full h-screen relative'>
            <div className='absolute top-3 left-3 flex gap-2'>
                <ThemeSwitcher />
                <LanguageSwitcher />
            </div>
            <div className='w-1/2 flex flex-col h-full justify-between py-8'>
                <form className='h-full grid place-items-center'>
                    <div className='w-1/2 h-full text-center flex flex-col justify-center align-items-center'>
                        <h2 className='text-4xl text-center font-bold mb-8'>{t('welcome')}</h2>
                        <Button
                            color='primary'
                            onClick={login}
                            className='text-2xl p-8 w-full flex align-items-center'
                            size='lg'
                            variant='shadow'
                        >
                            <img src='/images/google.png' className='w-12' />
                            <span className='font-bold'>{authenticateSettings.domain}</span>
                        </Button>
                        <Divider className='my-6' />
                        <p className=''>{t('org_email_requirements')}</p>
                    </div>
                </form>
                <Divider className='my-6 mx-auto w-1/2' />
                <div className='h-1/12 mx-auto w-1/3 flex justify-between text-md'>
                    <Link href={t.raw('link.website')} isBlock color='foreground'>
                        Веб-сайт
                    </Link>
                    <Link isBlock color='foreground'>
                        {t('link.youtube')}
                    </Link>
                    <Link isBlock color='foreground'>
                        {t('link.tiktok')}
                    </Link>
                </div>
            </div>

            <div className='w-1/2 h-full relative'>
                <img
                    className='w-full h-full object-cover object-center'
                    src={authenticateSettings.backgroundImage}
                    alt={`${authenticateSettings.domain}-background`}
                />
                <div className='absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 backdrop-blur-md p-6 rounded-xl bg-white/40'>
                    <img className='w-[500px]' src={authenticateSettings.logo} alt={`${authenticateSettings.domain}-logo`} />
                </div>
            </div>
        </div>
    );
};

export default Authenticate;

// src/scheduler-ui/src/app/auth/authenticate/authenticate.component.ts
import { Component, OnInit } from '@angular/core';

import { EMPTY, takeUntil } from 'rxjs';

import { GoogleLoginProvider, SocialAuthService } from '@abacritt/angularx-social-login';

import { BaseComponent } from '../../shared/components/base.component';
import { AuthService } from '../services/auth.service';

@Component({
    selector: 'uni-authenticate',
    templateUrl: './authenticate.component.html',
})
export class AuthenticateComponent extends BaseComponent implements OnInit {
    constructor(private socialAuthService: SocialAuthService, private authService: AuthService) {
        super();
    }

    ngOnInit(): void {
        this.socialAuthService.authState.pipe(takeUntil(this.destroy$)).subscribe((user) => {
            this.authService
                .authenticate({ email: user.email, picture: user.photoUrl, name: user.name })
                .pipe(takeUntil(this.destroy$))
                .subscribe((x) => console.log(x));
        });
    }

    login() {
        this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then(() => EMPTY);
    }
}

<div class='flex w-full h-screen relative'>

    <div class='w-1/2 flex flex-col h-full justify-between py-8'>
        <form class='h-full grid place-items-center'>
            <div class='w-1/2 h-full text-center flex flex-col justify-center align-items-center'>
                <h2 class='text-4xl text-center font-bold mb-4' translate="authenticate.welcome"></h2>
                <asl-google-signin-button class="flex justify-center items-center w-full text-center my-4"
                    shape="square" logo_alignment="center" type="standard" theme="filled_blue" size="large">
                </asl-google-signin-button>
                <p-divider />
                <p class="text-black/60 m-0" translate="authenticate.org_email_requirements"></p>
            </div>
        </form>
        <div class='h-1/12 mx-auto w-1/3 flex justify-between text-md'>
        </div>
    </div>

    <div class='w-1/2 h-full relative'>
        <img class='w-full h-full object-cover object-center' src="/assets/images/chnu-front.jpg" />
        <div
            class='absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 backdrop-blur-md p-6 rounded-xl bg-white/40'>
            <img class='w-[500px]' src="/assets/images/logo-chnu.svg" />
        </div>
    </div>
</div>
